function eval_css = C_analytical_pseudo_equi(E1,E2,T0,T1,T2,c0e,c1e,c2e,nu,beta,Keq1,Keq2)
%C_analytical_pseudo_equi
%    EVAL_CSS = C_analytical_pseudo_equi(E1,E2,T0,T1,T2,C0E,C1E,C2E,NU,BETA,Keq1,Keq2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Oct-2024 12:26:41

t2 = E2.*T1.*nu;
t3 = E2.*Keq2.*T2.*nu;
t4 = Keq2.*T1.*T2.*beta;
t6 = E2.*T2.*c2e.*nu;
t5 = c1e.*t2;
t7 = t2+t3+t4;
t8 = 1.0./t7;
eval_css = [0.0,t8.*(t5+t6+c1e.*t4),Keq2.*t8.*(t5+t6+T1.*T2.*beta.*c2e)];
