function eval_css = P2_analytical_pseudo_equi(E1,E2,T0,T1,T2,c0e,c1e,c2e,nu,beta,Keq1,Keq2)
%P2_analytical_pseudo_equi
%    EVAL_CSS = P2_analytical_pseudo_equi(E1,E2,T0,T1,T2,C0E,C1E,C2E,NU,BETA,Keq1,Keq2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Oct-2024 12:26:41

t2 = E1.*E2.*T0.*nu;
t4 = E1.*E2.*T2.*c2e.*nu;
t5 = E1.*Keq2.*T0.*T2.*beta;
t6 = E1.*E2.*Keq1.*Keq2.*T2.*nu;
t7 = E2.*Keq1.*Keq2.*T0.*T2.*beta;
t3 = c0e.*t2;
t8 = c0e.*t5;
t9 = t2+t5+t6+t7;
t10 = 1.0./t9;
eval_css = [t10.*(t3+t4+t8+c0e.*t7),Keq1.*t10.*(t3+t4+t8+E2.*T0.*T2.*beta.*c2e),Keq2.*t10.*(Keq1.*t3+Keq1.*t4+E1.*T0.*T2.*beta.*c2e+E2.*Keq1.*T0.*T2.*beta.*c2e)];
