function eval_css = vers_analytical_pseudo_equi(E1,E2,T0,T1,T2,c0e,c1e,c2e,nu,beta,Keq1,Keq2)
%VERS_ANALYTICAL_PSEUDO_EQUI
%    EVAL_CSS = VERS_ANALYTICAL_PSEUDO_EQUI(E1,E2,T0,T1,T2,C0E,C1E,C2E,NU,BETA,Keq1,Keq2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Oct-2024 12:26:40

t2 = beta.^2;
t3 = nu.^2;
t5 = E2.*Keq1.*T0.*T1.*beta.*nu;
t6 = E1.*Keq2.*T0.*T2.*beta.*nu;
t11 = E1.*Keq1.*Keq2.*T1.*T2.*beta.*nu;
t12 = E2.*Keq1.*Keq2.*T0.*T2.*beta.*nu;
t14 = E1.*Keq2.*T1.*T2.*beta.*c1e.*nu;
t4 = E1.*E2.*T0.*t3;
t7 = E1.*E2.*Keq1.*T1.*t3;
t9 = E1.*E2.*T1.*c1e.*t3;
t10 = E1.*E2.*T2.*c2e.*t3;
t13 = c0e.*t6;
t15 = E1.*E2.*Keq1.*Keq2.*T2.*t3;
t16 = Keq1.*Keq2.*T0.*T1.*T2.*t2;
t8 = c0e.*t4;
t17 = t4+t5+t6+t7+t11+t12+t15+t16;
t18 = 1.0./t17;
eval_css = [t18.*(t8+t9+t10+t13+t14+c0e.*t5+c0e.*t12+c0e.*t16),Keq1.*t18.*(t8+t9+t10+t13+t14+Keq2.*T0.*T1.*T2.*c1e.*t2+E2.*T0.*T1.*beta.*c1e.*nu+E2.*T0.*T2.*beta.*c2e.*nu),Keq2.*t18.*(Keq1.*t8+Keq1.*t10+c1e.*t5+c1e.*t7+Keq1.*T0.*T1.*T2.*c2e.*t2+E1.*T0.*T2.*beta.*c2e.*nu+E1.*Keq1.*T1.*T2.*beta.*c2e.*nu+E2.*Keq1.*T0.*T2.*beta.*c2e.*nu)];
